config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :tables
  resources :meals
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  scope :starters, -> { where(category: 'starter') }
  scope :mains, -> { where(category: 'main') }
  scope :desserts, -> { where(category: 'dessert') }
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :employee
  belongs_to :table
  has_many :order_meals
  has_many :meals, through: :order_meals
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end
end

app/controllers/order_meal.rb
class OrderMeal < ActiveRecord::Base
  belongs_to :order
  belongs_to :meal
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def index
    @tables = Table.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/index.html.erb
<h1 class="center">Employees</h1>
<% @employees.each do |employee| %>
  <p><%= employee.name %></p>
<% end %>

app/views/layouts/_header.html.erb
<%= link_to 'Employees', employees_path %>
<%= link_to 'Tables', tables_path %>
<%= link_to 'Meals', meals_path %>
<%= link_to 'Orders', orders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jimmys</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/meals/_meals.html.erb
<% meals.each do |meal| %>
  <div class="table meal">
    <p><%= meal.name %></p>
    <p><%= number_to_currency(meal.sale_price, unit: '£') %></p>
  </div>
<% end %>

app/views/meals/index.html.erb
<h1 class="center">Meals</h1>

<h2 class="center">Starters</h1>

<div class="tables">
  <%= render partial: 'meals', locals: { meals: @meals.starters } %>
</div>

<h2 class="center">Mains</h1>

<div class="tables">
  <%= render partial: 'meals', locals: { meals: @meals.mains } %>
</div>

<h2 class="center">Desserts</h1>

<div class="tables">
  <%= render partial: 'meals', locals: { meals: @meals.desserts } %>
</div>

app/views/orders/index.html.erb
<h1 class="center">Orders</h1>
<div class="tables">
  <% @orders.each do |order| %>
    <div class="table">
      <%= order.number %>
      <% order.meals.each do |meal| %>
        <p><%= meal.name %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/tables/index.html.erb
<h1 class="center">Tables</h1>
<div class="tables">
  <% @tables.each do |table| %>
    <div class="table table-<%= table.size %>">
      <h3>Table <%= table.number %></h3>
      <p>Seats <%= table.size %></p>
    </div>
  <% end %>
</div>